name: "Bastion Key Pair RDS SCP"

on:
  workflow_dispatch

jobs:
  deploy_vpc:
    name: "Deploy the VPC"
    runs-on: ubuntu-22.04
    defaults:
      run: 
        working-directory: bastion-to-rds
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::919980474747:role/github-actions
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply 
        run: terraform apply -auto-approve -input=false

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          terraform-bin output -json > tf-outputs.json
          echo "bastion_host=$(jq '.bastion_host.value' tf-outputs.json)" >> "$GITHUB_OUTPUT"
          echo "bastion_public_ip=$(jq '.bastion_public_ip.value' tf-outputs.json)" >> "$GITHUB_OUTPUT"
          echo "db_address=$(jq '.db_address.value' tf-outputs.json)" >> "$GITHUB_OUTPUT"
          echo "db_port=$(jq '.db_port.value' tf-outputs.json)" >> "$GITHUB_OUTPUT"
          echo bastion host: $(jq '.bastion_host.value' tf-outputs.json)
          echo bastion public ip: $(jq '.bastion_public_ip.value' tf-outputs.json)

      - name: Get DB Username
        id: get_db_username
        uses: IP-Sentinel/actions-aws-ssm-params-to-env@v1.4.0
        with:
          ssm-path: /app/bastions/POSTGRES_USER_NAME

      - name: Get DB Password
        id: get_db_password
        uses: IP-Sentinel/actions-aws-ssm-params-to-env@v1.4.0
        with:
          ssm-path: /app/bastions/POSTGRES_PASSWORD
          decryption: true 
          mask-values: true

      - name: Setup up data directory on bastion
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: steps.tf-outputs.outputs.bastion_host
          username: ubuntu
          port: 22 
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            rm -rf /home/user/test_data
            mkdir /home/user/test_data

      